spring:
  application:
    name: loadbalance
    
  cloud:
    config:
      server:
        git:
          uri: https://github.com/alberth270/SpringClound
          searchPaths: ConfigData
        native:
          searchLocations: classpath:offline-repository/

zuul:
  routes:
    users:
      path: /api/**
      service-id: service-atmdeposit
      
# Discovery Server Access
eureka:
  client:
    registerWithEureka: false
    service-url:
      defaultZone: http://localhost:8180/eureka/

server:
  port: 8080   # HTTP (Tomcat) port